// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockDBAdapter is a mock of DBAdapter interface.
type MockDBAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDBAdapterMockRecorder
}

// MockDBAdapterMockRecorder is the mock recorder for MockDBAdapter.
type MockDBAdapterMockRecorder struct {
	mock *MockDBAdapter
}

// NewMockDBAdapter creates a new mock instance.
func NewMockDBAdapter(ctrl *gomock.Controller) *MockDBAdapter {
	mock := &MockDBAdapter{ctrl: ctrl}
	mock.recorder = &MockDBAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBAdapter) EXPECT() *MockDBAdapterMockRecorder {
	return m.recorder
}
